### PR TITLE
Added navigation and minor changes

### PR DESCRIPTION
**Pull request by anand-ts**
Added navigation for business info (stylist details -> business info)
Changed global styles
Changed sign in auto correct

### CODE REVIEW

**Review by DavidHe137 — CHANGES_REQUESTED** [review]
Many bugs still. Don't merge yet.

**Review by achen443 — CHANGES_REQUESTED** [review]
we're working on this right now, just got in with anand

**Comment by achen443** [comment]
FYI the issue with the contentContainerStyles is due to globalStyles having alignItems and justifyContent. These are now commented out, so there shouldn't be any issues loading pages. We're fixing any alignment errors atm, just a heads up if you need to, you can override in the page itself

**Comment by anand-ts** [comment]
So, Andrew and I fixed the Client and Stylist details pages. We are now fixing on a navigation payload issue. After that, I will be plugging my Business Info page.

**Review by DavidHe137 — APPROVED** [review]

**Pull request merged**
