### PR TITLE
create directory page and associated navigation logic

### PR DESCRIPTION
**Pull request by willshutt**
- Created General Stylist Listing Component
- Listing Components are occupied by DB data on Directory page
- Stylist profile photos are able to be displayed in listing component
- Clicking a listing takes you to a stylist's business page

- Still needed: city filter

### CODE REVIEW

**Review by achen443 — APPROVED** [review]
logic looks good, page looks good

**Review by DavidHe137 — CHANGES_REQUESTED** [review]
Doesn't seem to work on my end. Maybe pulling my PRS from main messed some stuff up.

**Comment by achen443** [comment]
there was a merge conflict that i worked with after looking at the branch, i might have messed something up. i’ll work on it when i’m home, in augusta rn

**Comment by DavidHe137** [comment]
Ok I've fixed the errors with the directory, setting the default city of a client as Atlanta for now. Can you test and merge the Directory feature works?

**Review by DavidHe137 — APPROVED** [review]
I tested my changes and they seem to work.

**Review by achen443 — APPROVED** [review]

**Pull request merged**
