### PR TITLE
Geocoding with Address Validation

### PR DESCRIPTION
**Pull request by clarkcousins**
Stylists must input a valid US zip code upon account creation.
- zip code is stored in db
- extremely erroneous addresses are rejected

### CODE REVIEW

**Review by willshutt — CHANGES_REQUESTED** [review]
Recursive call somewhere is causing a call stack error on address validation

**Comment by willshutt** [comment]
looks good

**Review by anand-ts — APPROVED** [review]
Looks great, thanks Clark!

**Review by willshutt — APPROVED** [review]
looks good Clark

**Pull request merged**
